// Seed data for /news. Auto-generated news drafts go to admin queue per
// ANSWERS Q2.2; the `auto` flag is preserved on seeded items so the
// "🤖 AUTO" badge can render once the editorial queue lands.

import { colors } from '../tokens';

export type NewsKind = 'breaking' | 'releases' | 'ecosystem' | 'tutorials' | 'op-eds' | 'price';

export interface NewsItem {
  slug: string;
  kind: NewsKind;
  headline: string;
  summary: string;
  source: string;
  /** Coarse 'X ago' label for now; ISO timestamp lands with the DB. */
  time: string;
  /** Tile colour for breaking-news hero cards. */
  variant: 'mint' | 'uv' | 'yellow' | 'pink' | 'dark';
  topics: string[];
  /** Auto-generated by the news pipeline? Surfaces a 🤖 badge. */
  auto: boolean;
  body: string;
}

const VARIANT_TILE_COLOR: Record<NewsItem['variant'], string> = {
  mint:   colors.tileMint,
  uv:     colors.tilePurple,
  yellow: colors.tileYellow,
  pink:   colors.tilePink,
  dark:   colors.surface,
};

export function variantToTile(variant: NewsItem['variant']): string {
  return VARIANT_TILE_COLOR[variant];
}

const STANDARD_BODY = `The change rolled out earlier today. Existing consumers will see the new
behavior on the next billing cycle. No code changes are required — the
same slug returns at the new tier.

For users on Cursor or Claude Code, this represents a meaningful shift
in the per-session economics of agentic workflows. A typical refactor
session that previously cost $0.62 now lands closer to $0.43.

Affected resources, alternatives, and our cost calculator have already
updated.`;

const NEWS: NewsItem[] = [
  {
    slug: 'opus-47-price-cut',
    kind: 'breaking',
    headline: 'Claude Opus 4.7 input price dropped 30% today',
    summary:
      'Anthropic cut input pricing from $5/M to $3/M tokens. Output unchanged at $15/M.',
    source: 'auto',
    time: '2h ago',
    variant: 'mint',
    topics: ['Models', 'Anthropic'],
    auto: true,
    body: STANDARD_BODY,
  },
  {
    slug: 'cursor-05x-agents',
    kind: 'releases',
    headline: 'Cursor 0.5x ships background agents that work async',
    summary:
      'New agent mode runs in the background while you keep coding. Reads from a local queue.',
    source: 'Cursor blog',
    time: '14h ago',
    variant: 'dark',
    topics: ['Cursor', 'Models'],
    auto: false,
    body: STANDARD_BODY,
  },
  {
    slug: '21st-agents-sdk',
    kind: 'ecosystem',
    headline: '21st.dev ships an agents SDK for component generation',
    summary:
      'Programmable component generation from a natural-language brief. Available for Pro tier.',
    source: '21st.dev',
    time: '1d ago',
    variant: 'uv',
    topics: ['Components'],
    auto: false,
    body: STANDARD_BODY,
  },
  {
    slug: 'gemini-31-released',
    kind: 'releases',
    headline: 'Gemini 3.1 Pro lands with 2M-token context',
    summary: 'New flagship from Google. Cheaper than 2.5 Pro, faster on the same evals.',
    source: 'Google blog',
    time: '2d ago',
    variant: 'dark',
    topics: ['Models', 'Google'],
    auto: false,
    body: STANDARD_BODY,
  },
  {
    slug: 'mcp-spec-1-1',
    kind: 'ecosystem',
    headline: 'Model Context Protocol spec 1.1 introduces resource subscriptions',
    summary:
      'Long-running tools can now stream updates back to clients. Backwards compatible.',
    source: 'modelcontextprotocol.io',
    time: '3d ago',
    variant: 'dark',
    topics: ['MCPs'],
    auto: false,
    body: STANDARD_BODY,
  },
  {
    slug: 'qwen-3-coder',
    kind: 'releases',
    headline: 'Qwen 3 Coder 32B beats GPT-4.1 on SWE-Bench Verified',
    summary:
      'New open-weights coding model from Alibaba. Apache-2.0 licensed.',
    source: 'Alibaba',
    time: '4d ago',
    variant: 'yellow',
    topics: ['Models', 'Open weights'],
    auto: false,
    body: STANDARD_BODY,
  },
  {
    slug: 'tutorial-ollama-cursor',
    kind: 'tutorials',
    headline: 'How to run Qwen 3 Coder locally and pipe it into Cursor',
    summary:
      'Five-step guide: Ollama install, model pull, Cursor custom endpoint, latency tuning.',
    source: 'Vibe Coder Hub guides',
    time: '5d ago',
    variant: 'dark',
    topics: ['Open weights', 'Cursor'],
    auto: false,
    body: STANDARD_BODY,
  },
  {
    slug: 'oped-vibe-coding',
    kind: 'op-eds',
    headline: "Vibe coding isn't just a meme — it's the new abstraction layer",
    summary:
      'A short essay on why one-shot agents change the unit of work in software.',
    source: 'Vibe Coder Hub editorial',
    time: '1w ago',
    variant: 'pink',
    topics: [],
    auto: false,
    body: STANDARD_BODY,
  },
];

export function listNews(): NewsItem[] {
  return NEWS;
}

export function getNewsBySlug(slug: string): NewsItem | undefined {
  return NEWS.find((n) => n.slug === slug);
}

export const NEWS_KIND_LABELS: Record<NewsKind, string> = {
  breaking:  'Breaking',
  releases:  'Releases',
  ecosystem: 'Ecosystem',
  tutorials: 'Tutorials',
  'op-eds':  'Op-eds',
  price:     'Price changes',
};
